# Generated by Django 3.1.3 on 2020-11-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(default='', editable=False, max_length=50)),
                ('courseName', models.CharField(default='', editable=False, max_length=50)),
                ('info', models.CharField(default='', editable=False, max_length=500)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'AllCourse',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(default='', editable=False, max_length=50)),
                ('AnnouncementName', models.CharField(default='', editable=False, max_length=50)),
                ('info', models.CharField(default='', editable=False, max_length=500)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Announcement',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(default='', editable=False, max_length=50)),
                ('examName', models.CharField(default='', editable=False, max_length=50)),
                ('time', models.CharField(default='', editable=False, max_length=50)),
                ('info', models.CharField(default='', editable=False, max_length=500)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Exam',
            },
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(default='', editable=False, max_length=50)),
                ('HWName', models.CharField(default='', editable=False, max_length=50)),
                ('time', models.CharField(default='', editable=False, max_length=50)),
                ('info', models.CharField(default='', editable=False, max_length=500)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'HomeWork',
            },
        ),
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(default='', editable=False, max_length=50)),
                ('Question', models.CharField(default='', editable=False, max_length=500)),
                ('Answer', models.CharField(default='', editable=False, max_length=500)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'QA',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='', editable=False, max_length=50)),
                ('userName', models.CharField(default='', editable=False, max_length=50)),
                ('courses', models.CharField(default='', editable=False, max_length=500)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'UserData',
            },
        ),
    ]
