# Generated by Django 3.1.3 on 2020-11-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='userId',
            new_name='userEmail',
        ),
        migrations.AddField(
            model_name='userdata',
            name='isTeacher',
            field=models.BooleanField(default=False, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='userMajor',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='userPassword',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='userSchool',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
