# Generated by Django 3.1.3 on 2020-11-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_auto_20201121_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='courses',
            field=models.CharField(default=',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,', editable=False, max_length=1000),
        ),
    ]
